{{- if .Values.createGateway  -}}

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: operator-gateway
  namespace: {{ .Values.namespace }}

spec:
  gatewayClassName: traefik

  listeners:
    - name: websecure
      protocol: HTTPS
      port: 8443
      hostname: {{ .Values.frontend.host }}
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: frontend-server-tls

{{- end -}}
