# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: operator

image:
  repository: thomasherve/kube-game-core
  password: testpassword
  extension: ""
  pullPolicy: Always
  tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

instance:
  repository: thomasherve/kube-game-instance
  pullPolicy: Always
  tag: "latest"
  enabled: false 

frontend:
  repository: thomasherve/kube-game-frontend
  pullPolicy: Always
  backendProtocol: "http"
  tag: "latest"
  port: 80
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

redis:
  image: redis:7.2.5-alpine
  type: ClusterIP
  port: 6379
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8000

ingress:
  name: core
  enabled: false
  className: traefik
  hosts:
    - host: operator.backend.local
      path:  /
      pathType: Prefix
      name: core
      port: 8000
    - host: operator.frontend.local
      path:  /
      pathType: Prefix
      name: frontend
      port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  certificateauthoritydata:
  clientcertificatedata:
  clientkeydata:
  kubeaddress: 149.202.55.61

httpRoute:
  gatewayName: operator-gateway
  gatewayNamespace: operator
  enabled: true

  hosts:
    - host: operator.backend.local
      name: backend
      service: core
      port: 8000
    - host: operator.frontend.local
      name: frontend
      service: frontend
      port: 80