apiVersion: apps.thomas-herve.fr/v1alpha1
kind: GameInstancesManager
metadata:
  name: operator-game-manager
  namespace: {{ .Values.namespace }}
spec:
  hostname: {{ .Values.hostname }}
  instance:
    repository: {{ .Values.instance.repository }}
    pullPolicy: {{ .Values.instance.pullPolicy }}
    tag: {{ .Values.instance.tag | default .Chart.AppVersion }}
    internalPort: {{ .Values.instance.internalPort }}
  frontend:
    enabled: {{ .Values.frontend.enabled }}
    repository: {{ .Values.frontend.repository }}
    tag: {{ .Values.frontend.tag | default .Chart.AppVersion }}
    pullPolicy: {{ .Values.frontend.pullPolicy }}
    replicas: 1
    port: {{ .Values.frontend.port }}
    externalport: {{ .Values.frontend.port }}
    backendProtocol: https
    httpRouteEnabled: false
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
