{{- if .Values.real_operator }}
apiVersion: apps.thomas-herve.fr/v1alpha1
kind: GameInstancesManager
metadata:
  namespace: {{ .Values.namespace }}
spec:
  frontend:
    repository: {{ .Values.frontend.repository }}
    tag: {{ .Values.frontend.tag | default .Chart.AppVersion }}
    pullPolicy: Always
    replicas: 1
    port: {{ .Values.frontend.port }}
    backendURL: {{ (index .Values.httpRoute.hosts 0).host }}
    backendProtocol: https
    httpRouteEnabled: false
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
{{- end }}