apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev-controller-manager
  labels:
    app.kubernetes.io/instance: kube-game-operator
    app.kubernetes.io/name: kube-game-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/instance: kube-game-operator
        app.kubernetes.io/name: kube-game-operator
    spec:
      serviceAccountName: deployment-dev-clusterrole
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
