apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-dev-clusterrole
  namespace: operator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
  - apiGroups: ["apps.thomas-herve.fr"]
    resources: ["gameinstancesmanagers", "gameinstancesmanagers/status", "gameinstancesmanagers/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]