{{- if .Values.real_operator -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev-controller-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: deployment-dev-clusterrole
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.operator.watchNamespace | quote }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
{{- end }}