{{- if not .Values.real_operator -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-dev-clusterrolebinding
  namespace: operator
subjects:
- kind: ServiceAccount
  name: deployment-dev-clusterrole
roleRef:
  kind: Role
  name: deployment-dev-clusterrole
{{- end }}