# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: operator
hostname: game-frontend.thomas-herve.fr

frontend:
  repository: thomasherve/kube-game-frontend
  tag: "latest"
  port: 80
  enabled: true

instance:
  repository: thomasherve/kube-game-instance
  tag: "latest"
  internalPort: 8000
  pullPolicy: Always
