# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: operator

image:
  repository: thomasherve/kube-game-core
  password:
  extension: (/|$)(.*)
  pullPolicy: Always
  tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

instance:
  repository: thomasherve/kube-game-instance
  pullPolicy: Always
  tag: "latest"
  enabled: false 
  externalPort: 80
  internalPort: 8000

frontend:
  repository: thomasherve/kube-game-frontend
  pullPolicy: Always
  tag: "latest"
  port: 80
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

redis:
  image: redis:7.2.5-alpine
  type: ClusterIP
  port: 6379
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

